@startuml SHT31 use case diagram
left to right direction
actor User   as u
actor Sensor as s

package Library {
  usecase "Setup com bus"     as UC1
  usecase "Setup sensor"      as UC2
  usecase "Send data to user" as UC3
}
u   --> UC1
UC1 --> UC2
UC2 --> s
s   --> UC3
UC3 --> u
@enduml